---
- include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
  tags: vars, nginx

- include: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
  tags: vars, nginx

- name: installe nginx
  pkgng:
    name: nginx
    state: present
  tags: nginx, pkg

- name: enable nginx
  service:
    name: nginx
    enabled: yes
    state: started
  tags: nginx, rc

- block:
  - name: default config
    template:
      src: nginx.conf.j2
      dest: '{{ nginx_etcdir }}/nginx.conf'
    notify: restart nginx
  - name: servers.d dir
    file:
      dest: '{{ nginx_etcdir }}/{{ item }}'
      state: directory
      mode: '0750'
      owner: root
    with_items:
      - servers.d
      - modules.d
      - conf.d
    notify: restart nginx
  - name: default config parts
    template:
      src: 'nginx/{{ item }}.j2'
      dest: '{{ nginx_etcdir }}/{{ item }}'
    with_items:
      - servers.d/0default.conf
      - status.inc
    notify: restart nginx
  tags: nginx, config

# logs dir
- name: log dir
  file:
    dest: '{{ nginx_log_dir }}'
    owner: '{{ www_user }}'
    mode: '0750'
    state: directory
  when: 'nginx_log_dir != ""'
  tags: nginx, config

# reverse-proxy if any
- block:
  - name: config reverse-proxy
    lineinfile:
      dest: '{{ nginx_etcdir }}/fastcgi_params'
      line: '{{ item.line }}'
      regexp: '{{ item.regexp }}'
      state: present
    with_items:
      - { line: 'fastcgi_param  HTTPS $myhttps if_not_empty;', regexp: '^fastcgi_param\s+HTTPS' }
      - { line: 'fastcgi_param  REQUEST_SCHEME $myscheme if_not_empty;', regexp: '^fastcgi_param\s+REQUEST_SCHEME' }
    notify: restart nginx
  - name:
    template:
      src: nginx/modules.d/realip.conf.j2
      dest: '{{ nginx_etcdir }}/modules.d/realip.conf'
    notify: restart nginx
  when: '{{ proxified_by | count() }} > 0'
  tags: nginx, config

# x509 if needed
- block:
  - name: copie cachain
    copy:
      src: '{{ x509_cachain }}'
      dest: /etc/ssl/stapling.crt;
      mode: '0644'
    when: 'x509_cachain != ""'
  - name: x509 global config
    template:
      src: tls.inc.j2
      dest: '{{ nginx_etcdir }}/conf.d/tls.inc'
      mode: '0644'
  - name: check dhparam
    stat:
      path: /etc/ssh/dhparam4096.pem
      register: stat_dh
  - name: create dhparam
    command: 'openssl dhparam -out /etc/ssh/dhparam4096.pem 4096'
    when: not stat_dh.stat.exists
  when: 'do_tls == True'
  tags: nginx, config

- name: sites
  include: site.yml
  with_items: '{{ sites }}'
  loop_control:
    loop_var: onesite
  tags: nginx, sites

