---

- include_vars: site.yml

- name: site includes
  template:
    dest: '{{ nginx_etcdir }}/{{ item }}'
    src: '{{ lookup("first_found", include_locations) }}/{{ item }}'
  with_items: '{{ nginx_site.includes }}'
  when: '"includes" in nginx_site'

- name: conf includes
  copy:
    src: '{{ item }}'
    dest: '{{ nginx_etcdir }}/conf.d/{{ item | regex_replace(".*/([^/]+)$","\1") }}'
    mode: '0644'
  with_fileglob:
    - 'nginx/{{ nginx_site.id }}/conf.d/*.conf'

- name: root dir
  copy:
    dest: '{{ nginx_site.rootdir }}/'
    src: '{{ nginx_site.rootsrc }}/'
    mode: a=rX,u+w
    owner: root
  when: '"rootsrc" in onesite'

- name: mkdir root dir
  file:
    dest: '{{ nginx_site.rootdir }}'
    state: directory
    mode: '0755'
    owner: root
  when: '"rootsrc" not in onesite and "rootdir" in onesite'

- name: site config
  template:
    dest: '{{ nginx_etcdir }}/servers.d/{{ nginx_site.id }}.conf'
    src: '{{ lookup("first_found", siteconf_locations) }}'

- name: backend
  include_role:
    name: '{{ nginx_site.backend_role }}'
    vars:
      phpapps: 
        - '{{ nginx_site }}'
  when: '"backend_role" in nginx_site'
