---
# vars to define elsewhere (group_vars/, host_vars/, inventory, …) see 
# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence
#
# basedn LDAP
ldap_base: 'dc=univ,dc=fr'
# URI LDAP
ldap_uri: 'ldaps://ldapr.univ.fr/ ldaps://ldap.univ.fr/'
# openldap config directory
ldap_etcdir: /etc/ldap
# zsh path
zshpath: /bin/zsh
# mail relay to configure
mailrelay: smtp.local
# mail aliases file
mailaliases: /etc/aliases
# redirect mail for root to...
rootmailto: 
# x509 CA certificate
x509_ca_file:
# value for TLS_REQCERT in ldap.conf (and others)
ldap_tls_reqcert: never
