---
- name: install nginx
  pkgng:
    name: nginx
    state: present

- name: enable nginx
  lineinfile:
    dest: /etc/rc.conf
    line: 'nginx_enable="YES"'
    regexp: '^nginx_enable'
    state: present
