---
- include_vars: zone.yml

- name: get zone pattern
  shell: 'nsd-control zonestatus {{ zone.name }}'
  failed_when: False
  check_mode: False
  changed_when: False
  register: z
  when: 'zone.pattern != ""'

- name: delete zone
  command: 'nsd-control delzone {{ zone.name }}'
  when: 'zone.pattern != "" and z.rc == 0 and zone.pattern in nsd_patterns_list and "	pattern: "+zone.pattern not in z.stdout_lines'
  notify: reconfig nsd

- name: add zone
  command: 'nsd-control addzone {{ zone.name }} {{ zone.pattern }}'
  when: 'zone.pattern != "" and z.rc == 1 and zone.pattern in nsd_patterns_list'
  register: zadd
  notify: reconfig nsd

- debug:
   msg: 'Zone {{ zone.name }} modifiee ou ajoutee'
  when: 'zone.pattern != "" and z.rc == 1 and zone.pattern in nsd_patterns_list and zadd.changed'
