---
siteconf_locations:
  - '{{ playbook_dir }}/templates/apache/{{ apache_site.key }}/{{ apache_site.key }}.conf.j2'
  - '{{ playbook_dir }}/files/apache/{{ apache_site.key }}/{{ apache_site.key }}.conf'
  - 'templates/{{ apache_type }}/site.conf.j2'
  - templates/site.conf.j2

include_locations:
  - '{{ playbook_dir }}/templates/apache/{{ apache_site.key }}/{{ item }}.j2'
  - '{{ playbook_dir }}/files/apache/{{ apache_site.key }}/{{ item }}'
  - 'templates/apache/{{ apache_type }}/{{ item }}.j2'
  - 'templates/apache/{{ item }}.j2'
  - '{{ playbook_dir }}/files/apache/{{ item }}'

# site par defaut
default_site:
  key: default
  name: ''
  includes: []
  rootdir: '{{ apache_rootbase }}/{{ onesite.key }}'
  rootsrc: ''
  gitroot: ''
  group: '{{ apache_group }}'
  user: '{{ apache_user }}'
  grwfiles: []
  grwdirs: []

apache_site: '{{ default_site | combine(onesite) }}'
