---
- name: rc.conf
  lineinfile:
    dest: /etc/rc.conf
    line: '{{ item.key }}="{{ item.value }}"'
    regexp: '^{{ item.key }}='
  with_items:
    - { key: mysql_enable, value: "YES" }
    - { key: mysql_dbdir, value: '{{ mariadb_basedir }}' }

- name: zfs props
  zfs:
    name: '{{ mariadb_zfs_base }}'
    state: present
    mountpoint: '{{ mariadb_basedir }}'
    recordsize: 16K
  when: mariadb_zfs_base != ""

- name: my.cnf.j2
  template:
    src: my.cnf.j2
    dest: '{{ mariadb_basedir }}/my.cnf'
    mode: '0644'
    force: no

- name: install mariadb
  pkgng:
    name: '{{ item }}'
    state: present
  with_items:
    - mariadb{{ mariadb_version | regex_replace("[^0-9]","") }}-server
    - py27-MySQLdb
  register: install_mariadb
  when: 'ansible_os_family == "FreeBSD"'

- name: log dir
  file:
    dest: '{{ mariadb_logdir }}'
    state: directory
    mode: '0750'
    owner: '{{ mariadb_owner }}'
    group: '{{ mariadb_group }}'

- name: dbdir
  file:
    dest: '{{ mariadb_basedir }}'
    state: directory
    owner: '{{ mariadb_owner }}'
    group: '{{ mariadb_group }}'
    mode: 'ug+rwX,o-rwx'
    recurse: yes

# first install
- block:
  - name: start mariadb server
    service:
      name: '{{ mariadb_service }}'
      state: started
      enabled: yes
  - name: no test db
    mysql_db:
      name: test
      state: absent
  - mysql_user:
      name: ''
      host: localhost
      state: absent
  - mysql_user:
      name: ''
      host_all: yes
      state: absent
  - mysql_user:
      name: 'root'
      host: '127.0.0.1'
      state: absent
  - mysql_user:
      name: 'root'
      host: '::1'
      state: absent
  when: install_mariadb.changed

# default admins
- mysql_user:
    name: '{{ mariadb_admin_user }}'
    password: '{{ mariadb_admin_password }}'
    update_password: on_create
    host: '%'
    priv: '*.*:ALL,GRANT'
    state: present
  when: 'mariadb_admin_user != "" and mariadb_admin_password != ""'

- mysql_user:
    name: root
    password: '{{ mariadb_root_password }}'
    host: localhost
    append_privs: yes
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: yes
    state: present

- copy:
    dest: /root/.my.cnf
    mode: '0600'
    content: |
      [mysql]
      user=root
      {% if mariadb_root_password != "" %}password={{ mariadb_root_password }}{% endif %}
      [mysqladmin]
      user=root
      {% if mariadb_root_password != "" %}password={{ mariadb_root_password }}{% endif %}

# admin users
- mysql_user:
    name: '{{ item.name }}'
    priv: '{{ item.priv }}'
    host: '{{ item.host }}'
    password: '{{ item.password | default(item.name | hash("sha256")) }}'
    state: present
  with_items: '{{ mariadb_users | union(mariadb_maintenance_users) }}'

# DBs
- name: new dbs
  mysql_db:
    name: '{{ item.name }}'
    state: present
  with_items:
    - '{{ mariadb_dbs }}'
  when: 'mariadb_dbs | count > 0'

