---
# packages ecm
- block:
  - name: mkdir pkgrepo
    file:
      path: /usr/local/etc/pkg/repos
      state: directory
      mode: '0755'
  
  - name: pkg repo ecm
    copy:
      src: '{{ pkg_repo_conf }}'
      dest: '/usr/local/etc/pkg/repos/{{ pkg_repo_conf | regex_replace(".*/", "") }}'
      validate: 'pkg -vv -C %s'
      mode: '0644'
  when: pkg_repo_conf != ''
  tags: baseconf, pkg

# packages standard
- name: pkgs standard
  pkgng:
    name: '{{item}}'
    state: present
  with_items:
    - bsnmp-ucd
    - dmidecode
    - git
    - ipmitool
    - munin-node
    - rsync
    - smartmontools
    - tmux
    - vim-lite
    - zsh
    - openldap-sasl-client
    - '{{ pkgs }}'
  tags: baseconf, pkg

# mail via relay
- name: mailrelay
  lineinfile:
    dest: /etc/mail/freebsd.submit.mc
    line: "FEATURE(msp,[{{mailrelay}}])"
    regexp: '^FEATURE\(.?msp'
  register: domailrelay
  when: 'is_mailrelay != True and "{{mailrelay}}" != ""'
  tags: mailclient

- block:
  - name: stop sendmail
    service:
      name: sendmail
      state: stopped

  - name: config relay sendmail
    command: /usr/bin/make install-submit-cf
    args:
      chdir: /etc/mail

  - name: no sendmail_submit
    lineinfile:
      dest: /etc/rc.conf
      line: 'sendmail_submit_enable="NO"'
      regexp: '^sendmail_submit_enable='

  when: domailrelay.changed == True
  tags: mailclient

# timezone
- block:
  - name: get timezone
    command: cat /var/db/zoneinfo
    register: zoneinfo
    changed_when: False
    ignore_errors: True
    check_mode: False
  - name: set timezone
    command: 'tzsetup {{ host_timezone }}'
    when: zoneinfo.stdout != host_timezone
  tags: timezone

# syslog
- name: syslog central
  lineinfile:
    dest: /etc/syslog.conf
    line: '*.*			@{{ syslog_server }}'
    regexp: '^\*.\*@.*'
  when: '{{ syslog_server | default(False) | bool() }} and not {{ is_syslogd | default(False) }}'
  tags: syslog
  notify: restart BSD syslogd

# hardening freebsd
- block:
  - name: rc.conf
    lineinfile:
      dest: /etc/rc.conf
      regexp: '{{item.regexp}}'
      line: '{{item.line}}'
    with_items:
      - { regexp: '^clear_tmp_enable=', line: 'clear_tmp_enable="YES"' }
  - name:
    lineinfile:
      dest: /etc/sysctl.conf
      regexp: '{{item.regexp}}'
      line: '{{item.line}}'
    with_items:
      - { regexp: '^security.bsd.see_other_uids=', line: 'security.bsd.see_other_uids=0' }
  tags: security

# snmp
- name: config snmpd
  lineinfile:
    line: '{{ item.line }}'
    regexp: '{{ item.regexp }}'
    dest: /etc/snmpd.config
  with_items:
    - { line: 'begemotSnmpdModulePath."ucd" = "/usr/local/lib/snmp_ucd.so"', regexp: '^begemotSnmpdModulePath.*snmp_ucd' }
#    - { line: 'begemotSnmpdModulePath."hostres" = "/usr/lib/snmp_hostres.so"', regexp: '^begemotSnmpdModulePath.*snmp_hostres' }
  notify: restart bsnmpd
  when: '{{ is_jail }} == False'
  tags: baseconf, snmpd

- name: enable bsnmpd
  service:
    name: bsnmpd
    state: started
    enabled: yes
  when: '{{ is_jail }} == False'
  tags: baseconf, snmpd
