# all vars are defined by hand or defaulted by vars/app.yml
---

- include_vars: phpsite.yml

- debug: var=phpsite

- debug: var=fpm_site

- name: group
  group:
    name: '{{ fpm_site.group }}'
    state: present

- name: site user
  user:
    name: '{{ fpm_site.user }}'
    shell: /usr/sbin/nologin
    comment: 'php-fpm {{ fpm_site.name }}'
    home: /nonexistent
    createhome: no
    group: '{{ fpm_site.group }}'
    login_class: daemon
    state: present

- name: maintenance user
  user:
    name: '{{ fpm_site.maintainer }}'
    shell: /bin/sh
    home: '{{ fpm_site.home }}'
    comment: 'maintenance user for php {{ fpm_site.name }}'
    createhome: yes
    group: '{{ fpm_site.group }}'
  when: fpm_site.maintainer != ""

- name: fpm_site config
  template:
    src: fpm-site.conf.j2
    dest: '{{ fpm_pools_dir }}/{{ fpm_site.id }}.conf'

- name: mkdirs
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ fpm_site.id }}'
    group: '_{{ fpm_site.id }}'
    mode: '2770'
  with_items:
    - '{{ fpm_site.sessions_path }}'
    - '{{ fpm_site.tmpdir }}'
    - '{{ fpm_site.upload_dir }}'
  when: item | match("^/.*")

- name: nginx config
  include_role:
    name: nginx
  vars:
    sites: '[ {{ fpm_site }} ]'
  when: 'fpm_site.webserver_role == "nginx"'

- name: apache config
  include_role:
    name: apache
  vars:
    sites: '[ {{ fpm_site }} ]'
  when: 'fpm_site.webserver_role == "apache"'
