---
# install netmagis
- name: installe netmagis
  pkgng:
    name: '{{item}}'
    state: present
  with_items:
    - netmagis-database
    - netmagis-servers
    - netmagis-utils
    - netmagis-www
    - fcgiwrap
    - rancid3
  tags: pkg, netmagis

- name: patch netmagis/cas
  patch:
    src: netmagis_login.diff
    basedir: /
    strip: 1

- name: user netmagis
  user:
    home: /home/netmagis
    name: netmagis
    createhome: yes
    shell: /bin/sh
    state: present
  tags: user, netmagis

- name: reps netmagis
  file:
    dest: '/var/netmagis/{{ item }}'
    state: directory
    mode: 2770
    owner: root
    group: netmagis
  with_items:
    - ''
    - metro
    - eqvirt
    - eqgen
    - dnsmaster
    - dbdump
  tags: config, netmagis
    
- name: config netmagis
  template:
    src: netmagis.conf.j2
    dest: '{{ etcprefix }}/etc/netmagis.conf'
    mode: 0640
    owner: root
    group: netmagis
  tags: config, netmagis

- name: enable fcgiwrap netmagis
  template:
    src: netmagis_fastcgi.rc.j2
    dest: /etc/rc.conf.d/fcgiwrap
    mode: 0640
    owner: root
    group: 0
  tags: config, netmagis
  notify: restart fcgiwrap

- name: config nginx
  template:
    src: nginx_netmagis.conf.j2
    dest: '{{ etcprefix }}/etc/nginx/servers.d/netmagis.conf'
    mode: 0644
    owner: root
    group: 0
  tags: config, netmagis, nginx
  notify: restart nginx
