---
- name:
  pkgng:
    name: '{{ package }}'
    state: present
  with_items:
    - apache24
    - '{{ apache_freebsd_modules }}'
  loop_control:
    loop_var: package

- block:
  - name: enable modules
    lineinfile:
      dest: '{{ apache_etcdir }}/httpd.conf'
      line: 'LoadModule {{ item }}_module libexec/apache24/mod_{{ item }}.so'
      regexp: 'LoadModule\s+{{ item }}_module\s+.*'
    with_items: '{{ default_enabled_modules | union(apache_enabled_modules) | difference(default_disabled_modules | difference(apache_enabled_modules) | union(apache_disabled_modules)) }}'
  - name: disable modules
    lineinfile:
      dest: '{{ apache_etcdir }}/httpd.conf'
      regexp: '^\s*LoadModule\s+{{ item }}_module\s+libexec/apache24/mod_{{ item }}.so\s*$'
      state: absent
    with_items: '{{ default_disabled_modules | difference(apache_enabled_modules) | union(apache_disabled_modules) }}'

- name: enable apache24
  lineinfile:
    dest: /etc/rc.conf
    line: 'apache24_enable="YES"'
    state: present

- name: logrotate
  copy:
    dest: /usr/local/etc/newsyslog.conf.d/apache
    src: newsyslog.conf
    mode: '0640'
