---
siteconf_locations:
  - '{{ playbook_dir }}/templates/nginx/{{ nginx_site.id }}/{{ nginx_site.id }}.conf.j2'
  - '{{ playbook_dir }}/files/nginx/{{ nginx_site.id }}/{{ nginx_site.id }}.conf'
  - templates/site.conf.j2

include_locations:
  - '{{ playbook_dir }}/templates/nginx/{{ nginx_site.id }}'
  - '{{ playbook_dir }}/files/nginx/{{ nginx_site.id }}'
  - '{{ playbook_dir }}/files/nginx/{{ inventory_hostname |regex_replace("[0-9]$","") }}'
  - 'templates/nginx'
  - '{{ playbook_dir }}/files/nginx'

# site par defaut
default_site:
  id: default
  name: ''
  includes: []
  rootdir: '/home/{{ onesite.id }}/{{ onesite.id }}'
  rootsrc: ''
  listen: '80'
  x509_cert: ''
  x509_key: ''
  x509_chain: ''

nginx_site: '{{ default_site | combine(onesite) }}'

