---
# config client ldap Debian

- block:
  - name: config client LDAP Debian 8
    debconf:
      name: '{{item.name}}'
      question: '{{item.question}}'
      value: '{{item.value}}'
      vtype: '{{item.vtype}}'
    with_items:
      - { name: 'nslcd', question: 'nslcd/ldap-uris', vtype: 'string', value: '{{ldap_uri}}' }
      - { name: 'nslcd', question: 'nslcd/ldap-base', vtype: 'string', value: '{{ldap_base}}' }
      - { name: 'nslcd', question: 'nslcd/ldap-binddn', vtype: 'string', value: '{{ldap_binddn}}' }
      - { name: 'nslcd', question: 'nslcd/ldap-bindpw', vtype: 'string', value: '{{ldap_bindpw}}' }
      - { name: 'nslcd', question: 'nslcd/ldap-auth-type', vtype: 'select', value: 'simple' }
      - { name: 'nslcd', question: 'nslcd/ldap-cacertfile', vtype: 'string', value: '/etc/ssl/caecm.crt' }
      - { name: 'nslcd', question: 'nslcd/ldap-reqcert', vtype: 'string', value: 'demand' }
      - { name: 'nslcd', question: 'nslcd/ldap-starttls', vtype: 'boolean', value: 'true' }
      - { name: 'libnss-ldapd', question: 'libnss-ldapd/nsswitch', vtype: 'multiselect', value: 'passwd, group, shadow, automount' }
      - { name: 'libpam-ldapd', question: 'libpam-ldapd/enable_shadow', vtype: 'boolean', value: 'true' }

  - name: Installe client LDAP
    apt:
      name: '{{item}}'
      state: installed
    with_items:
      - nslcd
      - nslcd-utils
      - libnss-ldapd
      - libpam-ldapd
  when: (ansible_os_family == 'Debian' and ansible_distribution_major_version == '8')
  tags: nssldap
