---
siteconf_locations:
  - '{{ playbook_dir }}/templates/{{ site.id }}/apache/{{ site.id }}.conf.j2'
  - '{{ playbook_dir }}/files/{{ site.id }}/apache/{{ site.id }}.conf'
  - templates/site.conf.j2

include_locations:
  - '{{ playbook_dir }}/templates/{{ site.id }}/apache/{{ item }}.j2'
  - '{{ playbook_dir }}/files/{{ site.id }}/apache/{{ item }}'
  - 'templates/apache/{{ item }}.j2'
  - '{{ playbook_dir }}/files/apache/{{ item }}'

# site par defaut
default_site:
  id: default
  name: ''
  apache_includes: []
  rootdir: '{% if "rootsrc" in onesite or "gitroot" in onesite %}{{ apache_rootbase }}/{{ onesite.id }}{% endif %}'
  rootsrc: ''
  gitroot: ''
  group: '{{ www_group }}'
  user: '{{ www_user }}'
  grwfiles: []
  grwdirs: []
  tls: False
  tls_redir: False
  listen: '{% if "tls_cert" in onesite and onesite.tls_cert != "" %}*:443{% else %}*:80{% endif %}'
  default_index: 'index.html'
  status_path: '/apache-status'
  prefixes:
    - path: /
      allow_from_nets: []
  fcgi_status_path: ''

site: '{{ default_site | combine(onesite) }}'
