---
# tasks file for criecm.zfs
- include_tasks: '{{ includefile }}'
  with_first_found:
    - files:
        - '{{ ansible_os_family }}.yml'
  loop_control:
    loop_var: includefile
  tags: vars,zfs

- name: get zpools
  command: 'zpool list -H -o name'
  changed_when: False
  check_mode: False
  register: zpools
  tags: vars,zfs

- name: replication hosts
  include_tasks: zfs_backup.yml
  loop_control:
    loop_var: backup_host
    label: '{{ backup_host }}'
  delegate_to: '{{ backup_host }}'
  delegate_facts: True
  with_items: '{{ shares | selectattr("zfsrc","defined") | selectattr("backup_on","defined") | map(attribute="backup_on") | map("regex_replace","^.*@","") | list | unique }}'
  tags: zfs,replication

- name: zfs shares
  include_tasks: zfs.yml
  with_items: '{{ shares | selectattr("zfsrc","defined") | list }}'
  loop_control:
    loop_var: zfs
  tags: zfs
