---
- name: installe debconf-utils
  apt:
    name: debconf-utils
    state: installed
  when: ansible_os_family == 'Debian'
  tags: sysutils

- name: client openldap Debian
  apt:
    name: ldap-utils
    state: present
  tags: ldapconf

# mailrelay
- block:
  - name: installe postfix
    apt:
      name: postfix
      state: present

  - name: configure postfix
    debconf:
      name: "{{item.name}}"
      question: "{{item.question}}"
      value: "{{item.value}}"
      vtype: "{{item.vtype}}"
    with_items:
      - { name: 'postfix', question: 'postfix/root_address', value: 'root+{{ansible_nodename}}@{{maildomain}}', vtype: 'string' }
      - { name: 'postfix', question: 'postfix/mynetworks', vtype: 'string', value: '127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128' }
      - { name: 'postfix', question: 'postfix/mailname', vtype: 'string', value: '{{ansible_hostname}}.{{maildomain}}' }
      - { name: 'postfix', question: 'postfix/destinations', vtype: 'string', value: '{{ansible_fqdn}}, localhost, localhost' }
      - { name: 'postfix', question: 'postfix/relayhost', vtype: 'string', value: '{{mailrelay}}' }
      - { name: 'postfix', question: 'postfix/main_mailer_type', vtype: 'select', value: 'Satellite system' }
      - { name: 'postfix', question: 'postfix/procmail', vtype: 'boolean', value: 'false' }
    notify: reconfigure postfix

  when: "'mailrelay' not in group_names"
  tags: mailclient
