---
# packages ecm
- block:
  - name: mkdir pkgrepo
    file:
      path: /usr/local/etc/pkg/repos
      state: directory
      mode: 755
  
  - name: pkg repo ecm
    copy: src=pkgecm.conf dest=/usr/local/etc/pkg/repos/ecm.conf validate='pkg -vv -C %s' mode=644
  tags: pkgconf

# packages standard
- name: pkgs standard
  pkgng:
    name: '{{item}}'
    state: present
  with_items:
    - bsnmp-ucd
    - dmidecode
    - git
    - ipmitool
    - munin-node
    - rsync
    - smartmontools
    - tmux
    - vim-lite
    - zsh
    - openldap-client
  tags: pkgs

# mail via relay
- name: mailrelay
  lineinfile:
    dest: /etc/mail/freebsd.submit.mc
    line: "FEATURE(msp,[{{mailrelay}}])"
    regexp: '^FEATURE\(msp'
  register: domailrelay
  when: '"relaimail" not in group_names and "{{mailrelay}}" != ""'
  tags: mailclient

- block:
  - name: stop sendmail
    service:
      name: sendmail
      state: stopped

  - name: config relay sendmail
    command: /usr/bin/make install-submit-cf
    args:
      chdir: /etc/mail

  - name: no sendmail_submit
    lineinfile:
      dest: /etc/rc.conf
      line: 'sendmail_submit_enable="NO"'
      regexp: '^sendmail_submit_enable='

  when: domailrelay.changed == True

# hardening freebsd
- block:
  - name: rc.conf
    lineinfile:
      dest: /etc/rc.conf
      regexp: '{{item.regexp}}'
      line: '{{item.line}}'
    with_items:
      - { regexp: '^clear_tmp_enable=', line: 'clear_tmp_enable="YES"' }

  - name:
    lineinfile:
      dest: /etc/sysctl.conf
      regexp: '{{item.regexp}}'
      line: '{{item.line}}'
    with_items:
      - { regexp: '^security.bsd.see_other_uids=', line: 'security.bsd.see_other_uids=0' }

