---
# taches communes ECM

- name: Installe CA ECM
  copy:
    src: files/caecm.crt
    dest: /etc/ssl/caecm.crt
    owner: root
    group: 0
    mode: 0644
  tags: sslecm

- include_vars: 'vars/{{ansible_os_family}}.yml'

- include: 'tasks/{{ansible_os_family}}.yml'

- name: Config ldap.conf
  lineinfile:
    dest: '{{ldap_etcdir}}/ldap.conf'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  with_items:
    - { regexp: '^TLS_CACERT', line: 'TLS_CACERT /etc/ssl/caecm.crt' }
    - { regexp: '^TLS_REQCERT', line: 'TLS_REQCERT demand' }
    - { regexp: '^BASE', line: 'BASE {{ldap_base}}' }
    - { regexp: '^URI', line: 'URI {{ldap_uri}}' }
  tags: ldapconf

