---
# client openldap OpenBSD
- name: client openldap OpenBSD
  openbsd_pkg:
    name: openldap-client
    state: present
  tags: ldapclient

- name: openldap config dir
  file: path='{{ldap_etcdir}}' state=directory owner=0 group=0 mode=0755
  tags: ldapclient
