---
- name: client openldap OpenBSD
  openbsd_pkg:
    name: '{{item}}'
    state: present
  environment:
    PKG_PATH: "http://ftp.fr.openbsd.org/pub/OpenBSD/{{ansible_distribution_release}}/packages/{{ansible_architecture}}/"
  with_items:
    - openldap-client
    - git
    - munin-node
    - rsync
    - vim--no_x11
    - mtr--
    - zsh
  tags: baseconf, pkg

# config ldap globale
- name: openldap config dir
  file: path='{{ldap_etcdir}}' state=directory owner=0 group=0 mode=0755
  tags: ldapconf

# mailrelay
- name: mailrelay
  lineinfile:
    dest: /etc/mail/smtpd.conf
    line: 'accept from local for any relay via {{mailrelay}}'
    regexp: '^accept .*for any relay'
  notify: restart smtpd
  when: '"relaimail" not in group_names and "{{mailrelay}}" != ""'
  tags: mailclient

# timezone
- file: timezone
  src: '/usr/share/zoneinfo/{{ host_timezone }}'
  dest: '/etc/localtime'
  state: link
  force: yes
  tags: timezone

