---
- name: 'test -e {{ share.path }}'
  stat:
    path: '{{ share.path }}'
  register: path_stat

# create
- block:
  # need mkdir
  - name: mkdir
    file:
      path: '{{ share.path }}'
      state: directory
      owner: '{{ share.owner | default(omit) }}'
    when: '"zfsrc" not in share'
  when: not path_stat.stat.exists

- name: nfs export
  blockinfile:
    path: /etc/exports
    marker: '# {mark} ANSIBLE MANAGED BLOCK {{ share.path }}'
    block: |
      {% for ex in share.nfsshares %}
      {{ share.path }} {{ ex }}
      {% endfor %}
  notify: reload mountd

# cleanup zfs sharenfs props
- block:
  - command: 'grep ^{{ share.path }} /etc/zfs/exports'
    failed_when: False
    changed_when: False
    check_mode: False
    register: zexport
  - zfs:
      name: '{{ share.zfsrc }}'
      sharenfs: 'off'
      state: present
    when: zexport.rc != 0
  when: '"zfsrc" in share'
