---
- name: os vars
  include_vars: '{{ ansible_os_family }}.yml'
  tags: apache, vars

- name: install and enable apache
  import_tasks: '{{ ansible_os_family }}.yml'
  tags: apache, pkg

# conf standard
- block:
  - name: default confs
    file:
      dest: '{{ apache_etcdir }}/{{ item }}'
      state: directory
      mode: '0755'
    with_items:
      - '{{ apache_modsconfdir }}'
      - '{{ apache_sitesdir }}'
      - '{{ apache_includesdir }}'
  - name: conf includes
    copy:
      src: '{{ item }}'
      dest: '{{ apache_etcdir }}/{{ apache_includesdir }}/{{ item | regex_replace(".*/([^/]+)$","\1") }}'
      mode: '0644'
    with_fileglob:
      - 'apache/{{ apache_includesdir }}/*.conf'
      - '{{ inventory_hostname | regex_replace("[0-9]*$","") }}/apache/{{ apache_includesdir }}/*.conf'
      - '{{ inventory_hostname }}/apache/{{ apache_includesdir }}/*.conf'
  - name: conf modules
    copy:
      src: '{{ item }}'
      dest: '{{ apache_etcdir }}/{{ apache_modsconfdir }}/{{ item | regex_replace(".*/([^/]+)$","\1") }}'
      mode: '0644'
    with_fileglob:
      - 'apache/{{ apache_modsconfdir }}/*.conf'
      - '{{ inventory_hostname | regex_replace("[0-9]*$","") }}/apache/{{ apache_modsconfdir }}/*.conf'
      - '{{ inventory_hostname }}/apache/{{ apache_modsconfdir }}/*.conf'
  - name: conf .inc's
    copy:
      src: '{{ item }}'
      dest: '{{ apache_etcdir }}/{{ item | regex_replace(".*/([^/]+)$","\1") }}'
      mode: '0644'
    with_fileglob:
      - 'apache/{{ inventory_hostname }}/*.inc'
      - 'apache/*.inc'
  - name: conf include sites
    template:
      dest: '{{ apache_etcdir }}/{{ apache_includesdir }}/Zsites.conf'
      src: sites.conf.j2
      mode: '0644'
      force: no
  - name: apache default files
    copy:
      dest: '{{ apache_rootbase }}/default/'
      src: '{{ item }}/'
    with_first_found:
      - '{{ inventory_hostname }}/apache/default_root'
      - '{{ inventory_hostname | regex_replace("[0-9]*$","") }}/apache/default_root'
      - 'apache/default_root'
  tags: apache, config

- name: sites
  include_tasks: site.yml
  with_items: '{{ sites }}'
  loop_control:
    loop_var: onesite
  notify: restart apache
  tags: apache, sites

- name: start apache
  service:
    name: '{{ apache_service }}'
    state: started
  tags: apache, sites
