---
# config nfs services
- block:
  - apt:
    name: nfs-common
    state: present
  - name: lockd & callback ports
    copy:
      src: :etc:modprobe.d:nfs.conf
      dest: /etc/modprobe.d/nfs.conf
      mode: 600
      owner: root
  - name: statd port
    lineinfile:
      dest: /etc/default/nfs-common
      line: "{{ item }}"
    with_items:
      - 'STATDOPTS="-p 4047"'
      - 'NEED_STATD=yes'
      - 'NEED_IDMAPD=yes'
  - name: fix start-statd
    copy:
      src: :usr:sbin:start-statd
      dest: /usr/sbin/start-statd
      mode: 755
      owner: root
  - name: idmapd
    copy:
      src: :etc:idmapd.conf
      dest: /etc/idmapd.conf
      mode: 644
      owner: root
  notify: debian restart nfs all

# TODO: autofs LDAP
