---
# install filebeat FreeBSD

- name: install filebeat
  pkgng:
    name: filebeat
    state: present
  tags:
    - filebeat

- name: config
  copy:
    dest: /usr/local/etc/filebeat/filebeat.yml
    src: '{{ playbook_dir }}/files/{{ filebeat_type }}/filebeat.yml'
  notify: restart filebeat

- name: start filebeat
  service:
    name: filebeat
    state: started
