---
- name: install munin-server/freebsd
  pkgng:
    name: munin-master
    state: present

- name: config rrdcached
  lineinfile:
    dest: /etc/rc.conf
    line: 'rrdcached_flags="-U munin -s munin -m 0666 -l /var/run/rrdcached.sock -p /var/run/rrdcached.pid"'
    state: present
    regexp: '^rrdcached_flags'

- name: enable rrdcached
  service:
    name: rrdcached
    state: started
    enabled: yes
