---
- name: system-dependant vars if any
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - skip: True

- name: munin node
  include_tasks: node.yml
  when: munin_host != ''

- name: munin master
  include_tasks: master.yml
  when: munin_host | bool and munin_role == 'master' or (munin_host not in ansible_play_batch and munin_aggr_templates | count > 0)
  delegate_to: '{% if munin_host != inventory_hostname %}{{ munin_host }}{% else %}omit{% endif %}'
#  delegate_facts: True
