---
- name: install munin-node
  include_tasks: '{{ ansible_os_family }}-node.yml'

- name: munin allow servers
  lineinfile:
    dest: '{{ munin_etcdir }}/munin-node.conf'
    line: 'allow ^{{ munin_server | replace(".","\.") }}$'
    regexp: '^allow.*{{ munin_server | replace(".","\\.") }}\$$'
    insertafter: 'allow '
  notify: restart munin
  with_items:
    - '{{ munin_servers }}'
    - '127.0.0.1'
  loop_control:
    loop_var: munin_server

- include_tasks: node-plugins.yml

- name: enable munin service
  service:
    name: '{{ munin_service }}'
    state: started
    enabled: yes

- name: add config in munin server
  copy:
    dest: '{{ munin_host_dir }}/ansible-host-{{ inventory_hostname }}.conf'
    content: |
      [{{ ansible_fqdn }}]
      address {{ inventory_hostname }}
    force: no
  delegate_to: '{{ munin_host }}'
  when: munin_host != ''

